# Generated by Django 3.0.8 on 2020-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(max_length=100)),
                ('crime_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('police_station', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='criminals')),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=45)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('police_station', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_cases', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
