# Generated by Django 3.0.8 on 2020-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhaar_database',
            fields=[
                ('aadhaar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=20)),
                ('evidence_type', models.CharField(max_length=20)),
                ('evidence_file', models.FileField(upload_to='evidence')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('known', models.IntegerField()),
                ('unknown', models.IntegerField()),
                ('noone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('fir_id', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('fir_for', models.CharField(max_length=10)),
                ('o_relation', models.CharField(blank=True, max_length=30, null=True)),
                ('o_victim', models.CharField(blank=True, max_length=100, null=True)),
                ('o_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('fatherorhusbandName', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('police_station', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('complaint', models.TextField()),
                ('accused_description', models.TextField(blank=True)),
                ('suspected_criminal', models.CharField(blank=True, max_length=30, null=True)),
                ('evi', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(max_length=50)),
                ('io', models.CharField(blank=True, max_length=20, null=True)),
                ('volunteer', models.CharField(blank=True, max_length=12, null=True)),
                ('facilitator', models.CharField(blank=True, max_length=12, null=True)),
                ('compainant_signature', models.ImageField(blank=True, null=True, upload_to='signature')),
                ('sho_signature', models.ImageField(blank=True, null=True, upload_to='signature')),
                ('sho_reject', models.FileField(blank=True, null=True, upload_to='audio')),
                ('sp_reject', models.FileField(blank=True, null=True, upload_to='audio')),
                ('iochargesheet', models.FileField(blank=True, null=True, upload_to='chargesheet')),
                ('ioevidence', models.CharField(blank=True, max_length=1000, null=True)),
                ('affidavit', models.FileField(blank=True, null=True, upload_to='affidavit')),
            ],
        ),
        migrations.CreateModel(
            name='GETVolunteer',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('vid', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPValidator',
            fields=[
                ('otp', models.CharField(max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('file1', models.FileField(blank=True, null=True, upload_to='evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('aadhaar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('file1', models.FileField(blank=True, null=True, upload_to='evidence')),
                ('file2', models.ImageField(upload_to='signature')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('file1', models.FileField(blank=True, null=True, upload_to='evidence')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('aadhaar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('user_read', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
