# Generated by Django 3.0.8 on 2020-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotify',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('user_read', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
