# Generated by Django 3.0.8 on 2020-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usernotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaar_database',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='aadhaar_database',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature'),
        ),
    ]
