# Generated by Django 3.0.8 on 2020-08-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_fir_paadhaar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('transaction', models.CharField(max_length=1000)),
            ],
        ),
    ]
