# Generated by Django 3.0.8 on 2020-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_blockevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockevidence',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
