# Generated by Django 3.0.8 on 2020-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200802_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTable',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=12)),
                ('block', models.CharField(max_length=200)),
            ],
        ),
    ]
