# Generated by Django 3.0.8 on 2020-08-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_blocktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='curdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
